version: '3'
services:
  mariadb:
    image: mariadb
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_DATABASE=laboratoire
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports: 
      - "8081:8080"
  laboratoire-spring:
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes: 
      - .:/app